export const CHARACTER_GET_ALL_START = 'CHARACTER_GET_ALL_START';
export const CHARACTER_GET_ALL_SUCCESS = 'CHARACTER_GET_ALL_SUCCESS';
export const CHARACTER_GET_ALL_ERROR = 'CHARACTER_GET_ALL_ERROR';

export const CHARACTER_GET_START = 'CHARACTER_GET_START';
export const CHARACTER_GET_SUCCESS = 'CHARACTER_GET_SUCCESS';
export const CHARACTER_GET_ERROR = 'CHARACTER_GET_ERROR';
